 services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  mysql:
    image: mysql:8.4
    restart: unless-stopped
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    ports:
      - "6666:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
